'use client';
/* eslint-disable react-hooks/refs -- selection and editor refs are read only by toolbar event handlers. */

import { useLayoutEffect, useRef, useState } from 'react';
import { AlignCenter, AlignJustify, AlignLeft, AlignRight, Bold, CheckSquare, Code2, Image, IndentDecrease, IndentIncrease, Italic, Link, List, ListOrdered, Minus, Palette, Pilcrow, Quote, Redo2, RemoveFormatting, Strikethrough, Table2, Underline, Undo2, Video } from 'lucide-react';
import { cn } from '@/lib/utils';

export interface RichTextEditorProps { value: string; onChange: (value: string) => void; onBlur?: () => void; placeholder?: string; validationState?: 'valid' | 'invalid' }

export default function RichTextEditor({ value, onChange, onBlur, placeholder = 'Write a detailed description…', validationState }: RichTextEditorProps) {
  const editorRef = useRef<HTMLDivElement>(null);
  const imageInput = useRef<HTMLInputElement>(null);
  const [selectionRange, setSelectionRange] = useState<Range>();
  useLayoutEffect(() => { const editor = editorRef.current; if (editor && document.activeElement !== editor && editor.innerHTML !== value) editor.innerHTML = value; }, [value]);
  const rememberSelection = () => { const selection = window.getSelection(); if (selection?.rangeCount && editorRef.current?.contains(selection.anchorNode)) setSelectionRange(selection.getRangeAt(0).cloneRange()); };
  const run = (command: string, argument?: string) => { const selection = window.getSelection(); if (selectionRange && selection) { selection.removeAllRanges(); selection.addRange(selectionRange); } document.execCommand(command, false, argument); editorRef.current?.focus(); onChange(editorRef.current?.innerHTML ?? ''); rememberSelection(); };
  const insertTable = () => { const rows = Math.max(1, Number(window.prompt('Rows', '2')) || 2); const columns = Math.max(1, Number(window.prompt('Columns', '2')) || 2); run('insertHTML', `<table style="width:100%;border-collapse:collapse">${Array.from({ length: rows }, () => `<tr>${Array.from({ length: columns }, () => '<td style="border:1px solid #cbd5e1;padding:8px">Cell</td>').join('')}</tr>`).join('')}</table><p><br></p>`); };
  const uploadImage = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => run('insertImage', String(reader.result)); reader.readAsDataURL(file); };
  const buttons = [
    ['Undo', Undo2, () => run('undo')], ['Redo', Redo2, () => run('redo')], ['Bold', Bold, () => run('bold')], ['Italic', Italic, () => run('italic')], ['Underline', Underline, () => run('underline')], ['Strikethrough', Strikethrough, () => run('strikeThrough')],
    ['Text color', Palette, () => { const color = window.prompt('Text color (hex or CSS name)', '#0284C7'); if (color) run('foreColor', color); }], ['Add URL', Link, () => { const url = window.prompt('Enter URL', 'https://'); if (url) run('createLink', url); }], ['Upload image', Image, () => imageInput.current?.click()], ['Add video', Video, () => { const url = window.prompt('Video URL', 'https://'); if (url) run('insertHTML', `<video src="${url}" controls style="max-width:100%"></video><p><br></p>`); }],
    ['Table', Table2, insertTable], ['Quote', Quote, () => run('formatBlock', 'blockquote')], ['Code block', Code2, () => run('formatBlock', 'pre')], ['Horizontal line', Minus, () => run('insertHorizontalRule')], ['Paragraph break', Pilcrow, () => run('insertParagraph')],
    ['Align left', AlignLeft, () => run('justifyLeft')], ['Align center', AlignCenter, () => run('justifyCenter')], ['Align right', AlignRight, () => run('justifyRight')], ['Justify', AlignJustify, () => run('justifyFull')], ['Dotted bullets', List, () => run('insertUnorderedList')], ['Numbered list', ListOrdered, () => run('insertOrderedList')], ['Checklist', CheckSquare, () => run('insertHTML', '<ul class="checklist"><li>☐ Checklist item</li></ul>')], ['Indent', IndentIncrease, () => run('indent')], ['Outdent', IndentDecrease, () => run('outdent')], ['Remove formatting', RemoveFormatting, () => run('removeFormat')],
  ] as const;
  return <div className={cn('overflow-hidden rounded-xl border border-slate-300 bg-white shadow-sm focus-within:ring-2', validationState === 'valid' && 'border-green-500 ring-2 ring-green-100', validationState === 'invalid' && 'border-red-500 ring-2 ring-red-100', !validationState && 'focus-within:border-sky-500 focus-within:ring-sky-100')}>
    <div className="border-b border-slate-200 bg-slate-50">
      <div className="flex flex-wrap items-center gap-1 border-b border-slate-200 p-2"><select aria-label="Heading style" className="h-8 rounded-md border border-slate-200 bg-white px-2 text-xs" defaultValue="p" onFocus={rememberSelection} onChange={(event) => run('formatBlock', event.target.value)}><option value="p">Paragraph</option><option value="h1">Heading 1</option><option value="h2">Heading 2</option><option value="h3">Heading 3</option><option value="h4">Heading 4</option><option value="blockquote">Quote</option><option value="pre">Code</option></select><select aria-label="Font family" className="h-8 rounded-md border border-slate-200 bg-white px-2 text-xs" defaultValue="Arial" onFocus={rememberSelection} onChange={(event) => run('fontName', event.target.value)}><option>Arial</option><option>Georgia</option><option>Inter</option><option>Times New Roman</option><option>Courier New</option></select><select aria-label="Font size" className="h-8 rounded-md border border-slate-200 bg-white px-2 text-xs" defaultValue="3" onFocus={rememberSelection} onChange={(event) => run('fontSize', event.target.value)}><option value="1">10px</option><option value="2">12px</option><option value="3">14px</option><option value="4">18px</option><option value="5">24px</option><option value="6">32px</option><option value="7">48px</option></select></div>
      <div className="flex flex-wrap gap-1 p-2">{buttons.map(([label, Icon, action], index) => <span key={label} className="contents">{[2, 6, 10, 15, 19].includes(index) && <span className="mx-1 h-7 w-px bg-slate-300" />}<button type="button" title={label} aria-label={label} className="grid size-8 place-items-center rounded-md text-slate-500 hover:bg-white hover:text-sky-700 hover:shadow-sm" onMouseDown={(event) => event.preventDefault()} onClick={action}><Icon size={16} /></button></span>)}</div>
    </div>
    <input ref={imageInput} type="file" accept="image/*" className="hidden" onChange={(event) => { uploadImage(event.target.files?.[0]); event.target.value = ''; }} />
    <div ref={editorRef} dir="ltr" contentEditable suppressContentEditableWarning onBlur={onBlur} onMouseUp={rememberSelection} onKeyUp={rememberSelection} onInput={(event) => { onChange(event.currentTarget.innerHTML); rememberSelection(); }} data-placeholder={placeholder} className="rich-editor min-h-56 p-4 text-left text-sm leading-7 text-slate-700 outline-none [&_blockquote]:border-l-4 [&_blockquote]:border-sky-300 [&_blockquote]:pl-4 [&_h1]:text-3xl [&_h1]:font-bold [&_h2]:text-2xl [&_h2]:font-bold [&_h3]:text-xl [&_h3]:font-semibold [&_img]:max-w-full [&_ol]:list-decimal [&_ol]:pl-6 [&_pre]:rounded-lg [&_pre]:bg-slate-900 [&_pre]:p-3 [&_pre]:text-white [&_table]:my-3 [&_ul]:list-disc [&_ul]:pl-6" />
  </div>;
}
